### ISSUE TITLE
open source licence

### ISSUE THREAD

**Issue by stanleypa** [QuadCorei8085/elero_protocol#6]
I got a request to add an open source license to my repo but as I re-used some of your code I don't want to use one that would conflict.  Can you please apply an open source license to your code?

**Comment by QuadCorei8085** [comment]
Do i have to insert it into every file/code or is this a github option?

**Comment by QuadCorei8085** [comment]
added MIT license to the repo as github described it: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by stanleypa** [comment]
Thanks
